### ISSUE TITLE
CAS Service not avaiolable

### ISSUE THREAD

**Issue by pavankumarkatakam** [CenterForOpenScience/docker-library#17]
Hi, i just cloned it and done `docker-compose up -d` from the cas folder, now when i visited to url `https://localhost:8433` the below shown error appearing any help.
![cas](https://cloud.githubusercontent.com/assets/6078669/13217104/1cd56f8e-d986-11e5-873c-6b1fb0f53a92.png)

**Comment by pavankumarkatakam** [comment]
Docker container status is Up and running.

**Comment by HalcyonChimera** [comment]
what happens if you go to localhost:8080?

**Comment by binoculars** [comment]
Stale
